
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://padvgqklusymcguevusa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhZHZncWtsdXN5bWNndWV2dXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjM1ODksImV4cCI6MjA2NDYzOTU4OX0.MsjpaxS1VjPKE6yRMHBFRsYGA1uaY-2vgz2N7ks_EdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
